[Refactor] Animator Refactoring
KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends pull request #375
Opened 2023-07-11 07:47 UTC by lees5402

# PR을 하기 전 체크사항

- [x] 임시로 작성한 코드는 모두 제거했나요?
- [x] 주석은 충분히 작성했나요?
- [x] 실행했을 때, 오류는 없나요?
- [x] 커밋 메시지는 [가이드](https://docs.google.com/document/d/1bDgWctGEprMvLzV5OpuZV1-BCnrhVVJ19cd8D9tFArU/edit#heading=h.jgj6vfjils4q)에 맞춰 작성됐나요?

# 변경된 기능

- 목록 1 LegendController와 LegendAnimationController 컴포넌트만 사용하도록 하였습니다. 

# 제안 사항

- 목록 1 플레이어의 관여하는 스크립트를 Controller와 AnimationController로 통합하였습니다.
> 컴포넌트를 줄임으로써 관리가 용이하도록 하기 위함

# 관련 이슈
이번 변경과 관련된 이슈가 있다면 아래에 작성해주세요.

- [x] #358

2023-07-11 09:26 UTC, ChoiSeonMun requested changes
다시 바꾸십시오.

2023-07-11 09:26 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +            _rigidbody.AddForce(JUMP_DIRECTION * MAX_JUMP_POWER, ForceMode.Impulse);
점프 상태로 로직 옮기는 게 좋을 듯.

2023-07-11 09:26 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        if (isJump)
Idle 상태에서 모든 트리거를 초기화한다면 이 코드도 의미가 없음.

2023-07-11 09:26 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +            other.transform.forward = (-1) * transform.forward;
다른 객체를 조작하는 것은 버그의 온상임.

2023-07-11 09:26 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private void FixedMaxFallSpeed()
`FixedMaxFallSpeed` 이름이 비직관적임.

2023-07-11 09:26 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private void FixedMaxFallSpeed()
`ClampFallSpeed`, `LimitFallSpeed` 혹은 최대 낙하속도를 제한한다라는 의미가 더 분명히 드러났으면 좋겠음.

2023-07-11 09:26 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        if (_rigidbody.velocity.y <= 0f)
```suggestion
if (IsFalling())
{
  if (IsExceeded(velocity, maxSpeed))
  {
     MakeMaxSpeed(_rigidbody);
  }
}
```

형태의 코드가 되었으면 함.

2023-07-11 09:26 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    #region 각 공격별 HitZone 생성
각 HitZone을 열거형과 배열로 관리가 되었으면 함.

2023-07-11 09:44 UTC, lees5402 commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        Physics.gravity = new Vector3(0f, -_gravitationalAcceleration, 0f);
프로젝트 세팅에서 수정함

2023-07-11 10:48 UTC, lees5402 commented on ItaCH_Smash_Legends/Assets/Script/LegendAnimationController.cs
> +    public void AttackAnimation(ComboAttackType comboAttackType)
PlayAttackAnimation 으로 함수명을 변경

2023-07-11 10:49 UTC, lees5402 commented on ItaCH_Smash_Legends/Assets/Script/LegendAnimationController.cs
> +    public void TriggerAnimation(int animationHash)
관련함수 삭제

2023-07-11 10:49 UTC, lees5402 commented on ItaCH_Smash_Legends/Assets/Script/LegendAnimationController.cs
> +    public void TrueAnimation(int animationHash)
관련함수 삭제함

2023-07-11 10:49 UTC, lees5402 commented on ItaCH_Smash_Legends/Assets/Script/LegendAnimationController.cs
> +    public void FalseAnimation(int animationHash)
관련함수 삭제함

2023-07-11 10:50 UTC, lees5402 commented on ItaCH_Smash_Legends/Assets/Script/LegendAnimationController.cs
> +    public void PlayAnimation(int animationhash)
관련함수 삭제함

2023-07-12 08:13 UTC, ChoiSeonMun requested changes
UniTask로 작성된 로직을 각 상태의 업데이트로 옮길 수 없는지 고려하세요.

2023-07-12 08:13 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        if (RollingForward.x > 0)
```
enum RollingDirection { Front, Back }
```

위와 같은 열거형을 만듭니다.

2023-07-12 08:13 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        if (RollingForward.x > 0)
RollingForward와 MoveDirection을 기반으로 RollingDirection을 반환하는 함수를 만듭니다.

```
RollingDirection GetDirection(Vector2 rollingForward, Vector2 moveDirection)
    {
        if (rollingForward.x > 0)
        {
            if (moveDirection.x > 0)
            {
                return RollingDirection.Back;
            }
            else
            {
                return RollingDirection.Front;
            }
        }
        else
        {
            if (moveDirection.x < 0)
            {
                return RollingDirection.Back;
            }
            else
            {
                return RollingDirection.Front;
            }
        }
    }
```

2023-07-13 01:58 UTC, gitLeejw commented on ItaCH_Smash_Legends/Assets/Script/LegendAnimationController.cs
> +    public Animator Animator { get; private set; }
관련 기능 수정했습니다.

2023-07-13 04:34 UTC, ChoiSeonMun requested changes
제발 커밋 전 본인 스스로 코드 리뷰 하고서 나한테 오세요.

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    public CancellationTokenSource TaskCancel;
요거 왜 public?

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +            transform.forward = SetHangRotation(other.transform.position);
함수 이름은 SetHangRotation인데 반환값이 있음. 함수명 부적절.

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +            transform.position = SetHangPosition(other);
상동

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +            OnConstraints();
머하는 함수인지 모르겠

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    public void GetKnockbackOnAttack(Collider other, int animationHash, KnockbackType type)
함수 이름 부적절함. Get이 들어가지만 void 타입임. 반환값이 없다면 로직을 설명하는 이름이어야 함.

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private float SetKnockbackPower(KnockbackType type, Collider other)
함수명 부적절

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private Vector3 SetHangRotation(Vector3 other)
함수명 부적절

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private Vector3 SetHangPosition(Collider other)
함수명 부적절

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        float _hangPositionY = 2.5f;
```suggestion
        float hangPositionY = 2.5f;
```

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        for (int i = 0; i < hangPosition.Length; ++i)
foreach 문 혹은 Array.ForEach()를 사용하세요.

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        {
이 본문을 왜 하는지 잘 모르겠습니다. 함수로 만들어주세요.

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private Vector3 SetHangPosition(Collider other)
함수 본문이 너무 긺

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private void OnConstraints()
함수명 부적절

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        _rigidbody.constraints = RigidbodyConstraints.None;
이 구문을 왜 하는 것?

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    public void OffConstraints()
함수명 부적절

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    public void OffConstraints()
얘는 왜 public이고 OnConstraints()는 왜 private

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    public async UniTaskVoid OnFalling(Animator animator)
```suggestion
    public async UniTaskVoid FallAsync(Animator animator)
```

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/PlayerHangController.cs
이건 삭제해주세요.

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
> +    // 회의 후 생존 및 삭제 여부 결정
이런 내용은 이슈로 발행하세요. 주석에 쓰지 말고

2023-07-13 04:34 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Player_State/LegendHangState.cs
> +        if (legendController.IsTriggered(ActionType.Jump))
문라이터 PlayerState 참고해서 개선할 수 없는지 생각해볼 것

2023-07-13 08:51 UTC, ChoiSeonMun reviewed
각 상태에서 어떤 로직이 동작되는지 한번에 이해하기가 어려움.
다만, 머지하고 추후에 이 부분 고려해서 코드가 작성되면 좋을 듯.
물론 LegendController에서 모든 걸 처리한다고 합의가 되었다면 OK

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +            transform.forward = GetHangRotation(other.transform.position);
forward에 Rotation 값을 넣는다는 게 어색함. 함수명 교체 권고.

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private void SetMaxSpeed()
다른 곳에서 쓰이는 게 아니라면 로컬 함수로 만드는 걸 추천.

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private bool IsExceededSpeed() => _rigidbody.velocity.magnitude > _maxFallingSpeed;
이것도 다른 메소드에서 호출되는 부분이 없다면 로컬 함수로 변경하는 걸 권장.

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        if (_moveDirection != Vector3.zero)
```
if (_moveDirection == Vector3.zero)
{
  return;
}
```
으로 하면 불필요한 개행 안해도 됨.

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        if (_moveDirection != Vector3.zero)
또한 Vector3.zero를 호출할 때마다 새로운 영벡터를 생성하기에 조금 더 성능을 고려한다면 영벡터를 캐싱하는 게 좋음.

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private float GetHangPositionValue(float value)
로컬 함수로 권장

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +    private float GetHangPositionValue(float value)
GetHangPositionValue() 라는 함수명이 뭔가...부족함 와닿지 않음. 아래의 구문을 왜 하는지 잘 모르겠음. 좀 더 서술바람.

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Player_State/LegendDownIdleState.cs
> +        legendController.StartRollingAsync().Forget();
함수 이름 그냥 RollAsync() 하면 되는 거 아니냐구..

2023-07-13 08:51 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Player_State/LegendDownIdleState.cs
해당 상태에서 어떤 일이 일어나는지 한번에 이해하기가 어려움.

2023-07-13 10:34 UTC, merged