#12356
KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends pull request #376
Opened 2023-07-11 07:50 UTC by stalepatt

# PR을 하기 전 체크사항

- [x] 임시로 작성한 코드는 모두 제거했나요?
- [x] 주석은 충분히 작성했나요?
- [x] 실행했을 때, 오류는 없나요?
- [x] 커밋 메시지는 [가이드](https://docs.google.com/document/d/1bDgWctGEprMvLzV5OpuZV1-BCnrhVVJ19cd8D9tFArU/edit#heading=h.jgj6vfjils4q)에 맞춰 작성됐나요?

# 변경된 기능

- 캐릭터 프리팹 리소스 로드 시 이미 로드 했던 프리팹은 Dictionary로 접근해서 가져옵니다.

# 제안 사항

- 캐릭터 프리팹을 불러올 때 GameObject가 아닌 CharacterStatus 컴포넌트로 접근합니다.
> 다른 게임 오브젝트들과 구별하여 캐릭터 프리팹만 Dictionary에 저장하기 위함입니다.

# 관련 이슈

- [x] #356

2023-07-11 07:51 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/Data/ResourcesManager.cs
경로 변경

2023-07-11 07:52 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/Manager/Managers.cs
> +                gameObject = new GameObject { name = "@Managers" };
대소문자 오타

2023-07-12 01:33 UTC, ChoiSeonMun requested changes
1. 코드 컨벤션 오류가 계속 보이는데 커밋하기 전 반드시 재검토 바랍니다. 이건 리뷰어한테 괜히 약점 잡히는 꼴
2. CharacterStatus 스크립트는 굉장히 불필요해보이고, 코드 결합도를 높이는 데 일조하고 있는 것으로 보입니다. 재설계를 반드시 진행하세요.

2023-07-12 01:33 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/ResourcesManager.cs
> +    public Dictionary<string, CharacterStatus> _legends = new Dictionary<string, CharacterStatus>();
상동

2023-07-12 01:33 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/ResourcesManager.cs
> +                return sprite as T;
```suggestion
{
  return sprite as T;
}
```

2023-07-12 01:33 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/ResourcesManager.cs
> +            if (_legends.TryGetValue(path, out CharacterStatus characterStatus))
이 부분은 왜 _legends에 추가하지 않는지?

2023-07-12 01:33 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/ResourcesManager.cs
> +            Debug.Log($"Failed to load prefab : {path}");
```suggestion
            Debug.LogError($"Failed to load prefab : {path}");
```
로그를 좀 더 구분하여 사용할 것.

2023-07-12 01:33 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/ResourcesManager.cs
> +            return;
중괄호가 없음.

2023-07-12 01:33 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
재설계 필요.

2023-07-14 01:09 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs
> +    protected readonly string HEAVY_BULLET_DELETE_EFFECT_PATH = FilePath.HeavyBulletDeleteEffect;
@gitLeejw 와 상의하여 수정 예정

2023-07-14 01:12 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/PlayerMove.cs
> +    private LegendController _characterStatus;
구버전 레거시 파일
사라질 스크립트

2023-07-14 01:13 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
> +    protected LegendController characterStatus;
구버전 레거시
사라질 파일

2023-07-14 06:05 UTC, ChoiSeonMun reviewed
1. 코드 컨벤션...
2. 주석 처리 대신에 코드 삭제 후 이슈 발행하길 바랍니다.

리뷰를 반영해도 좋고 반영하지 않아도 좋습니다.

2023-07-14 06:05 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Stage/Team.cs
팀은 멤버 관리만 하면 되지 않나.

2023-07-14 06:05 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/User/UserManager.cs
> +        UserLocalData = new UserData();
AllUserData가 이미 LocalData를 포함하는 데이터인데, 굳이 중복하여 만들고 있음.

2023-07-14 06:05 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/User/UserManager.cs
> +        UserLocalData = new UserData();
네트워크 전용 데이터라면 네트워킹 전용 클래스에서 진행하는 것이 맞음.

2023-07-17 06:37 UTC, ChoiSeonMun reviewed
일관된 코드를 위해서 개선을 권고합니다.

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Data/UserData.cs
> +    public GameModeType SelectGameMode { get; set; }
GameMode가 UserData라고는 보이지 않는데.

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Data/UserData.cs
> +    public Team Team { get; set; }
GameRoom에서 관리하는 것이 좋아보임.

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
> +        void GetComponents()
????????? 로컬 함수 남용 금지

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/LegendController.cs
여기 있는 것처럼 로컬 함수 쓰면 메모리 추가적으로 사용함.

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        for (int i = 0; i < _currentGameMode.MaxPlayer; ++i)
```suggestion
        for (int player = 0; player < _currentGameMode.MaxPlayer; ++player)
```

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        Team GetTeamAvailable()
변수를 캡쳐하는 순간 Local Function은 Delegate처럼 동작하기 때문에 Heap Allocation을 유발합니다.
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions#heap-allocations

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        Team GetTeamAvailable()
```suggestion
        static Team GetTeamAvailable(List<Team> teams)
```

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        LegendController legend = Managers.ResourceManager.GetLegendPrefab(user.SelectedLegend);
함수 이름은 `GetLegendPrefab`인데 반환 타입이 `LegendController`라 약간 어색합니다.
왜냐하면 일반적으로 Prefab의 타입은 GameObject라고 생각하기 때문이죠.

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        LegendController legend = Managers.ResourceManager.GetLegendPrefab(user.SelectedLegend);
함수명을 고치던, API를 고치던 해야 할 것으로 보입니다.

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        LegendController legend = Managers.ResourceManager.GetLegendPrefab(user.SelectedLegend);
하지만...이번 변경에는 굳이 반영하지 않아도 됩니다.

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        GameObject legendObject = Managers.ResourceManager.Instantiate(legend.gameObject, spawnPoint);
위의 구문을 함께 처리할 수 있는 API를 만들 수 있을 것으로 생각되는데..

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/StageManager.cs
> +        GameObject legendObject = Managers.ResourceManager.Instantiate(legend.gameObject, spawnPoint);
```
public GameObject Instantiate(string prefabPath, Transform spawnTransform) 
```

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Manager/UserManager.cs
이거 자체가 GameRoomManager의 역할로 보이는데..

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs
> +        var legend = other.GetComponent<LegendController>();
여태껏 등장하지 않던 var를..?

2023-07-17 06:37 UTC, ChoiSeonMun commented on ItaCH_Smash_Legends/Assets/Script/Util/Path.cs
>              StringBuilder stringBuilder = new StringBuilder();
아직도 stringBuilder를 매번마다 생성하네

2023-07-20 06:29 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/User/UserManager.cs
> +        UserLocalData = new UserData();
현재 #293 에서 재구성 완료

2023-07-20 06:30 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
Damage 처리를 제외하고 재구성 완료.
#355 또는 후속 작업에서 Hitzone 작업 완료 시 삭제

2023-07-20 06:47 UTC, stalepatt commented on ItaCH_Smash_Legends/Assets/Script/Manager/Managers.cs
상기 했듯 GameRoomManager 삭제

2023-07-20 06:57 UTC, merged